export const PATHS = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FACE_CAPTURE: '/register/face-capture',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_OTP: '/verify-otp',
  NEW_PASSWORD: '/new-password',
  REGISTRATION_SUCCESS: '/registration-success',
  ONBOARDING: '/onboarding',
  PSYCHOLOGIST: '/psychologist/:id',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:id',
  ARTICLE: '/articles',
  ARTICLE_DETAIL: '/articles/:id',
  NEWS: '/news',
  NEWS_DETAIL: '/news/:id',
  GALLERY: '/gallery',
  TRAININGS: '/trainings',
  EXPERTS: '/experts',
  JOURNAL: '/journal', // Public Landing Page Journal

  // Unified App Paths
  SESSIONS: '/sessions',
  SESSION_VERIFY_FACE: '/sessions/:id/verify-face',
  SESSION_CALL: '/sessions/:id/call',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  NOTIFICATIONS: '/notifications',
  EXPERT_DETAIL: '/experts/:id',
  MINI_GAMES: '/mini-games',
  BREATHING_GAME: '/mini-games/play',

  // Legacy / Webapp Aliases pointing to unified routes
  DASHBOARD: '/',
  WEBAPP_JOURNAL: '/journal',
  WEBAPP_SESSIONS: '/sessions',
  WEBAPP_SESSION_VERIFY_FACE: '/sessions/:id/verify-face',
  WEBAPP_SESSION_CALL: '/sessions/:id/call',
  WEBAPP_MEDIA: '/gallery',
  WEBAPP_ENLIGHTENMENT: '/articles',
  WEBAPP_PROFILE: '/profile',
  WEBAPP_SETTINGS: '/settings',
  WEBAPP_NOTIFICATIONS: '/notifications',
  WEBAPP_GALLERY: '/gallery',
  WEBAPP_NEWS: '/news',
  WEBAPP_NEWS_DETAIL: '/news/:id',
  WEBAPP_BLOG: '/blog',
  WEBAPP_BLOG_DETAIL: '/blog/:id',
  WEBAPP_ARTICLE: '/articles',
  WEBAPP_ARTICLE_DETAIL: '/articles/:id',
  WEBAPP_TRAININGS: '/trainings',
  WEBAPP_EXPERTS: '/experts',
  WEBAPP_EXPERT_DETAIL: '/experts/:id',
  WEBAPP_MINI_GAMES: '/mini-games',
  WEBAPP_BREATHING_GAME: '/mini-games/play',
};

