export const PATHS = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_OTP: '/verify-otp',
  NEW_PASSWORD: '/new-password',
  REGISTRATION_SUCCESS: '/registration-success',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  JOURNAL: '/journal',
  PSYCHOLOGIST: '/psychologist/:id',
  BLOG: '/blog',
  ARTICLE: '/articles',
  NEWS: '/news',
  NEWS_DETAIL: '/news/:id',
  GALLERY: '/gallery',
  TRAININGS: '/trainings',
} as const;

