export { HeroSection } from './HeroSection';
export { FeaturesSection } from './FeaturesSection';
export { PillarsSection } from './PillarsSection';
export { TestimonialsSection } from './TestimonialsSection';
export { RoadmapSection } from './RoadmapSection';
export { PartnersSection } from './PartnersSection';
export { VrConsultationSection } from './VrConsultationSection';
export { CtaSection } from './CtaSection';
export { ExpertsSection } from './ExpertsSection';
